# Generated by Django 4.2.3 on 2023-07-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fad',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
