# Generated by Django 4.2.3 on 2023-07-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fad',
        ),
        migrations.AlterField(
            model_name='decade',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='decade',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
