# Generated by Django 4.2.7 on 2023-11-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_fads'),
    ]

    operations = [
        migrations.AddField(
            model_name='fads',
            name='description',
            field=models.CharField(default='no description', max_length=100),
        ),
    ]
