# Generated by Django 4.2.3 on 2023-07-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_delete_fad_alter_decade_end_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.TextField()),
                ('description', models.CharField(max_length=250)),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decade', to='nostaldja.decade')),
            ],
        ),
    ]
