# Generated by Django 4.2.7 on 2023-11-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_fads_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fads',
            name='decade',
            field=models.CharField(default='no decade', max_length=100),
        ),
        migrations.AddField(
            model_name='fads',
            name='image_url',
            field=models.CharField(default='no image', max_length=100),
        ),
    ]
