# Generated by Django 4.2.3 on 2023-07-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_fad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fad',
            name='decade',
        ),
        migrations.AlterField(
            model_name='decade',
            name='end_year',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='decade',
            name='start_year',
            field=models.CharField(max_length=100),
        ),
    ]
