# Generated by Django 4.2.7 on 2023-11-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0004_fads_decade_fads_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fads',
            old_name='name',
            new_name='year',
        ),
    ]
