# Generated by Django 4.2.7 on 2023-11-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0005_rename_name_fads_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fads',
            name='year',
        ),
    ]
