# Generated by Django 4.2.3 on 2023-07-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0005_fad_decade_alter_fad_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fad',
        ),
    ]
