# Generated by Django 4.2.3 on 2023-07-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fasds',
            new_name='Fads',
        ),
    ]
